# H2 en archivo (persistente) con AUTO_SERVER (permite múltiples conexiones)
spring.datasource.url=jdbc:h2:file:./data/vetcare;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivamos el console web (ya no lo necesitas)
spring.h2.console.enabled=false
